<?php
$pessoa = array(
    'usuario' => '',
    'nome' => '',
    'data_nascimento' => '',
    'celular_numero' => '',
    'sexo' => '',
    'escolaridade' => '',
    'estado_civil' => '',
    'nacionalidade' => '',
    'possui_filhos' => '',
    'possui_deficiencia' => '',
    'pais' => '',
    'estado' => '',
    'cidade' => '',
    'cnh' => '',
    'ultimo_salario_mensal' => '',
    'empregado_atualmente' => '',
    'procurando_emprego_atualmente' => '',
    'disponivel_viagens' => '',
    'trabalha_outras_cidades' => '',
    'trabalha_exterior' => '',
    'trabalha_home_office' => '',
    'possui_carro' => '',
    'possui_moto' => ''
);