<?php
echo '<div class="linha">';
echo '<div class="coluna esquerda">';
echo '<a href="index.php">Home</a><br>';
echo '<a href="registro.php">Registrar</a><br>';
echo '<a href="login.php">Entrar</a><br>';
echo '<a href="logoff.php">Sair</a><br>-<br>';
echo '<a href="../controller/pessoa.php?a=c">Dados Pessoais</a><br>';
echo '<a href="curso.php">Cursos</a><br>';
echo '<a href="certificacao.php">Certificação</a><br>';
echo '<a href="experiencia_profissional.php">Experiência Profissional</a><br>';
echo '<a href="objetivo_profissional.php">Objetivo Profissional</a><br>';
echo '<a href="idioma.php">Idiomas</a><br>';
echo '<a href="habilidade.php">Habilidades</a><br>';
echo '<a href="vagas.php">Pesquisar Vagas</a><br>';
echo '<a href="curriculo.php">Exibir Currículo</a><br>-<br>';
echo '<a href="publicar_vaga.php">Publicar Vaga de Emprego</a><br>-<br>';
echo '<a href="servicos.php">Cadastrar Serviços</a><br>-<br>';
echo '<a href="servicos_pesquisa.php">Pesquisar Serviços</a>';
echo '</div>';