<div class="linha">
   <div class="coluna esquerda">
      <a href="index.php">Home</a><br>
      <a href='usuario.php'>Registrar</a><br>
      <a href='login.php'>Entrar</a><br>
      <a href='#'>Sair</a><br>-<br>
      <a href="pessoa.php">Dados Pessoais</a><br>
      <a href="curso.php">Cursos</a><br>
      <a href="certificacao.php">Certificação</a><br>
      <a href="experienciaprofissional.php">Experiência Profissional</a><br>
      <a href="objetivoprofissional.php">Objetivo Profissional</a><br>
      <a href="idioma.php">Idiomas</a><br>
      <a href="habilidade.php">Habilidades</a><br>
      <a href="vagas.php">Pesquisar Vagas</a><br>
      <a href="curriculo.php">Exibir Currículo</a><br>
      <a href="curriculo.php">Testes de Personalidade</a><br>-<br>
      <a href="publicarvaga.php">Publicar Vaga de Emprego</a><br>-<br>
      <a href="servico.php">Serviços</a><br>
      <a href='#'></a>Provas<br>
      <a href="#.php">Apostilas</a><br>
      <a href="#">Livros</a><br>
      <a href="#">Treinamentos</a><br>
   </div>