<div class="sidenav">
<a href="../index.php">BitCurriculos</a><br>
    <a href="../index.php">Home</a><br>
    <a href="pessoa.php">Dados Pessoais</a><br>
    <a href="#">Objetivo Profissional</a><br>
    <a href="#">Cursos</a><br>
    <a href="#">Certificados</a><br>
    <a href="#">Experiência Profissional</a><br>
    <a href="#">Idiomas</a><br>
    <a href="#">Habilidades</a><br>
    <a href="#">Vagas</a><br>
    <a href="#">Exibir Currículo</a><br>
    <a href="#">Selecionar Candidatos</a><br>
    <a href="#">Publicar Vaga</a><br>
    <a href="#">Login Pessoas</a><br>
    <a href="#">Login Empresas</a><br>
    <a href="#">Fale Conosco</a><br>
    <a href="#">Sair</a>
</div>